service: INHA-CC-<<YOUR NUMBER>>-GET-CHAT
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  iam:
    role:
      name: lambda-role-scan-dynamodb
      path: /custom-role-path/
      statements:
        - Effect: "Allow"
          Resource: "arn:aws:dynamodb:ap-northeast-2:${file(../serverless.env.yml):ACCOUNT_ID}:table/${file(../serverless.env.yml):DYNAMO_TABLE_NAME}"
          Action: "dynamodb:Scan"

functions:
  postMessage:
    handler: index.handler
    url:
      cors: true
    timeout: 900
    memorySize: 1024
    environment: # serverless.env.yml에 정의한 환경 변수를 여기에 등록
      DYNAMO_TABLE_NAME: ${file(../serverless.env.yml):DYNAMO_TABLE_NAME}
